name: Build and Deploy c3woc website

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Cache lfs data
      uses: actions/cache@v1
      with:
        path: ~/.git
        key: |
          0
          1
          2
          3
          4
          5
          6
          7
          8
          9
          lfs
    - name: install git-lfs
      run: |
        sudo apt-get install git-lfs
        sudo apt-get autoremove
    - name: pull lfs data
      run: git lfs pull
    - name: build with lektor
      run: |
        pip install lektor
        # stop the build if there are Python syntax errors or undefined names
        lektor build -f scss 
    - name: deploy new site
      run: |
        echo 'c3woc.de ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC5NslYj+wtriBuKIxJfDRm9E2hnlstWR8durQ6pKvVvP7wjcoXIyAxe41GvJ9SoEhSjF7oVlzlw+zAkzl5WOZ4=' | sudo tee /etc/ssh/ssh_known_hosts
        lektor deploy --key $LEKTOR_DEPLOY_KEY c3woc
